name: Run Docss Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any other dependencies your script needs here

    - name: Run Docss.py
      run: python ScholarshipCreditsCodes/Docss.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/ScholarshipCreditsCodes/credentials.json
